### ISSUE TITLE
Not an issue - just a question

### ISSUE THREAD

**Issue by kevinroberts** [commandtab/brewbot#1]
Hi,

I stumbled upon your project by chance and I happen to have built a very similar device for my office which uses a capacitive touch sensor as a trigger instead of a current measuring device. I was just wondering how you determined the current draw of your coffee maker and also curious what kind of coffee maker you have? We have an industrial coffee maker and it goes through various different cycles when heating and brewing but I'm interesting in trying to get the current sensor method working.

Thanks! Kevin

**Comment by command-tab** [comment]
Hi!

This project uses an inductive current sensor which, after some math, can tell you fairly accurately how much current the instrumented device is drawing. When idle, our commercial coffee maker pulls well under 1 Amp. When boiling water, it pulls something like 13 Amps, so the rise in draw is very noticeable. It occasionally gets fooled if several people make tea in quick succession, since it needs to boil more water but hasn’t made coffee. To the sensor, though, it’s all the same, but that doesn’t happen often.

One key aspect is seeing the rise in power draw, waiting a minute, measuring again, and repeating that several times before sending the notification. This avoids sending false notifications when the machine is just keeping water hot; It doesn’t boil for three or four minutes just to maintain heat.

Hope that helps!

**Comment by kevinroberts** [comment]
That does thanks for the response. I have to get in and start measuring ours. Good tip on the repeat measuring checks.
